# Generated by Django 2.1.5 on 2019-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_image',
            field=models.ImageField(default='default.jph', upload_to='recipe_pics'),
        ),
    ]
