# Generated by Django 2.1.5 on 2019-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0002_post_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipe_image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
    ]
